### ISSUE TITLE
Not enough permissions to load / subscribe to CoValue

### ISSUE THREAD

**Issue by bdparrish** [garden-co/classic-jazz#1953]
### Description
A user that has been invited to a CoValue that does not have access to all CoValue children fails the invite - `Not enough permissions to load / subscribe to CoValue`

### Reproduce
1. Create root CoValue
2. Root CoValue has a field that is a CoList - `channels` in this example
3. The CoList group extends the root CoValue group
4. Add a CoValue to the CoList that is only accessible to one of the current members of the CoList
5. Invite a new user
6. Observe that the invite fails because the new user cannot load / subscribe to the CoValue in the CoList that was added  in step 4

### Expectation
I would expect the invited user has access to all available CoValues, CoList, etc that is the root CoValue group or extends the root CoValue group.

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/88a6dbe2-0ff0-4295-ac74-214f0d2aa63d" />

**Comment by bdparrish** [comment]
schema.tsx

``` javascript
import { Account, CoList, CoMap, Group, co } from "jazz-tools";

export class Item extends CoMap {
    name = co.string;
}

export class ListOfItems extends CoList.Of(co.ref(Item)) { }

export class Organization extends CoMap {
    name = co.string;
}

export class List extends CoMap {
    name = co.string;
    items = co.ref(ListOfItems)
    organization = co.ref(Organization)
}

export class ListOfLists extends CoList.Of(co.ref(List)) { }

export class BaseAccountRoot extends CoMap {
    lists = co.ref(ListOfLists);
    currentList = co.optional.ref(List)
    currentItem = co.optional.ref(Item)
}

export class BaseAccount extends Account {
    root = co.ref(BaseAccountRoot);

    async migrate(this: BaseAccount, creationProps?: { name: string }) {
        const meGroup = Group.create({ owner: this })

        if (this.root === undefined) {
            this.root = BaseAccountRoot.create(
                {
                    lists: ListOfLists.create([], meGroup)
                },
                meGroup,
            );
        }
    }
}

```

addList
```javascript
const addItem = (name: string, organization: Organization) => {
    const orgGroup = organization._owner as Group
    const listGroup = Group.create({ owner: me })
    orgGroup.extend(listGroup)

    const list = List.create({
      name,
      organization
    }, { owner: listGroup })

    const item = Item.create(
      {
        name: 'todo',
      },
      { owner: listGroup }
    )

    workspace.items = ListOfItems.create([list], { owner: listGroup })

    me.root.lists.push(list)
    me.root.currentList = list
    me.root.currentItem = item
}
```

addItem
```javascript
const addItem = (name: string, isPrivate: boolean) => {
    const listGroup = me.root.listWorkspace!._owner as Group
    const itemGroup = Group.create({ owner: me })

    if (!isPrivate) {
      itemGroup.extend(listGroup)
    }

    const item = Item.create({
      name
    }, { owner: itemGroup })

    me.root.currentList.items.push(item)
    me.root.currentItem = item
}
```

**Comment by bdparrish** [comment]
https://github.com/bdparrish/jazz-inheritance

1. Create List

<img width="1443" alt="Image" src="https://github.com/user-attachments/assets/15c69017-f02b-41d7-bf8e-5d6a92f56edf" />

2. Invite a new user

![Image](https://github.com/user-attachments/assets/9130c956-d35e-4d17-aa19-9c4c90abe3c0)

3. Add a Item CoValue to the CoList that is only accessible to one of the current members of the CoList

![Image](https://github.com/user-attachments/assets/5f1d342f-7686-4bb5-a442-7ab2b8c365ac)

4. Invite a new user

![Image](https://github.com/user-attachments/assets/9130c956-d35e-4d17-aa19-9c4c90abe3c0)

5. Observe that the invite fails because the new user cannot load / subscribe to the CoValue in the CoList that was added in step 4

**Comment by bdparrish** [comment]
because I am trying to load all of the `items`. if I replace the `{ $each: true }` with `true`, then everything works as expected for what I need, but I would expect that it should not matter when I load all items or not. it should ignore those items that I am `unauthorized` to see.

this only gets me half way there. when the createBrowserContext is called it fails again.

```
  useAcceptInvite({
    invitedObjectSchema: List,
    onAccept: useCallback(
      async (listID: ID<List>) => {
        const list = await List.load(listID, { resolve: { items: { $each: true } } }) // <<< issue is here

        const me = await BaseAccount.getMe().ensureLoaded({
          resolve: {
            root: true
          },
        });

        if (me?.root) {
          const found = me.root.lists?.find((w: co<List | null>) => {
            if (w!.id == listID) {
              return w
            }
          })

          if (!found && list) {
            me.root.lists!.push(list!)
            me.root.currentList = list
          }

          navigate("/")

          return <p>Routing to List - {me.root.currentList?.name}</p>;
        } else {
          return <p>Checking List - {list?.name}</p>;
        }
      },
      [navigate],
    ),
  });
```

**Comment by gdorsi** [comment]
Thanks for opening the issue, going to give it a look today!

**Comment by gdorsi** [comment]
Fix released on Jazz 0.13.9

**Comment by bdparrish** [comment]
@gdorsi - I am still seeing issues. upgraded to `0.13.13` - I updated the example app repo linked in this ticket

```
Not enough permissions to load / subscribe to CoValue co_z6b6rbEtVL9hrFSYkQaSafrXeQU on path items.1 unaccessible value: co_zTpRPGrmRdKwcUGLEzhLoDHcjsj
Promise.then		
(anonymous)	@	main.tsx:42
```

**Comment by gdorsi** [comment]
@bdparrish 

Does it work if you mark the list refs as optional?

```ts
class MyCoList extends CoList.Of(co.optional.ref(MyCoMap)) {}
```

Is having null values on the list expected for you?

**Comment by gdorsi** [comment]
@bdparrish 

Are you still experiencing this issue?

**Comment by bdparrish** [comment]
@gdorsi this can be closed for now
